name: DynamicWorlds
author: CapitainFoxy
version: 1.0
main: com.capitainfoxy.dynamicworlds.DynamicWorlds
commands:
  world:
    description: Create and manage worlds
    usage: /<command> <create>
